### ISSUE TITLE
Essential characteristics

### ISSUE THREAD

**Issue by fhkjaerskov** [usnationalarchives/digital-preservation#12]
Thank you for sharing your digital preservation framework which is both informative and truly inspiring in terms of community involvement. We sometimes struggle narrowing down essential characteristics. Can you elaborate on how you proceed with this? In short, how do you do it?

**Comment by lljohnston** [comment]
There is some records appraisal philosophy that goes into defining what characteristics are "essential," so it may vary from institution to institution dependent on concepts of what characteristics have value. And of course a characteristic may have value when part of one record type but not another. And it can be impacted by institutional attitudes towards records, specifically, whether the focus is preserving the information or if there is a desire to preserve the look and feel of a record. Our current institutional mindset is to prioritize the preservation of the record content over the original user interaction or full look and feel when the latter is not feasible. 

The core of the work was identifying the four categories of characteristics that we considered vital: Appearance, Behavior, Context, and Structure. For each of the record types we identified which categories of characteristics were the highest priority, such as Appearance being a higher priority for still images and not as much for textual records. 

Our subject matter specialist processing archivists then applied their own knowledge of processing and/or transforming files for preservation and public use. In some cases we started with the specific - essential characteristics of some specific file formats/software packages - and generalized up to the more inclusive record types. In other cases we developed the record type characteristics and confirmed those assumptions as we developed plans for the specific formats. The plans are are best informed opinions based on practice - we've been accessioning born-digital records since 1970. 

One note about a useful resource: for the Still Image, Audio, and Video materials we viewed it through a lens of format sustainability that relied on much of the FADGI guidance and some of the work being done within the Working Groups.
