### ISSUE TITLE
Plain-text preferred formats

### ISSUE THREAD

**Issue by dangormanjr** [usnationalarchives/digital-preservation#32]
I noticed that .odt files are listed as a preferred text-based format, but other versions like .rtf and .txt aren't included. Why is that?

**Comment by lljohnston** [comment]
.txt is the extension - we do have ASCII identified as a Preferred format for textual records. 

We have analyzed RTF as a low risk format to retain, but our appraisal group has not identified it as a Preferred or Acceptable format for transfers from agencies. We can ask someone from that group to explain the reasoning. We will follow up with an answer.

**Comment by lljohnston** [comment]
I have an answer from our agency guidance team. Their principles for identification of Preferred and Acceptable formats including avoiding, if possible, proprietary formats which are not open source and have no open accessible standards, as well as formats that federal agencies are not actively transferring. RTF falls under all 3 of those categories so is not considered Preferred or Acceptable. 

There are some proprietary formats in the Transfer Guidance because of the sheer ubiquity of those formats, such as Microsoft Word .doc. The need to identify a version that is acceptable for transfer overrides its proprietary nature which would normally mean that it is excluded.

We have RTF in our Plans because we have received files in smallish amounts in Presidential records transfer.

**Comment by dangormanjr** [comment]
Thanks for explaining more about the criteria for file preservation.
