### ISSUE TITLE
Action plans per format rather than PDF of category

### ISSUE THREAD

**Issue by nkrabben** [usnationalarchives/digital-preservation#6]
For linking and reference purposes, it would be helpful to have action plans for each format saved to a separate file. It would also be helpful to have a text based format option like markdown or html.

**Comment by lljohnston** [comment]
We struggled with the formatting of the plans for this draft public comment release because we wanted them to be inclusive of the higher level record type and the essential characteristics of that record type, which also aligns with how we categorize our transfer guidance. 

I completely agree that the full release iterations after this comment period is over need to be marked up in a way that they can be parsed out and linkable by format.

**Comment by lljohnston** [comment]
I should add that I'd very much appreciate suggestions as to the markup strategies that would be the most useful for the community.
