### ISSUE TITLE
EPUB?

### ISSUE THREAD

**Issue by TAC-NISO** [usnationalarchives/digital-preservation#7]
I find it odd that the EPUB specification is not at all referenced in this document.  As a W3C Recommendation, as a forthcoming ISO standard, and as a publishing/web format that is widely used in publication distribution, I am surprised to see it not listed in this document.  

More information about the current EPUB version 3.2 is available at: https://www.w3.org/publishing/epub32/epub-spec.html

The ISO standardization project (based on 3.0.1) ISO/IEC TS 30135-1:2014
Information technology — Digital publishing — EPUB3 — Part 1: EPUB3 Overview - https://www.iso.org/standard/53255.html

**Comment by lljohnston** [comment]
The simple answer is that we haven't received transfers of ePub files from federal agencies as permanent records so we didn't analyze the risk of something we don't yet have in our holdings in this go round. We also don't have as many publications in our holdings as both GPO and LOC which have the preservation of publications as their regulatory mandate. I'll make sure we add ePub to our analysis when we do our next revision, because we want to be proactive as we develop these plans to cover formats we expect to receive.
