### ISSUE TITLE
Machine-Readability

### ISSUE THREAD

**Issue by OwenAmbur** [usnationalarchives/digital-preservation#9]
The framework should take into account the direction set forth in the OPEN Government Data Act (OGDA) to make records machine-readable by default, based upon standardized schemas. https://www.linkedin.com/pulse/open-gov-data-act-machine-readable-records-owen-ambur/

**Comment by lljohnston** [comment]
We do make unclassified datasets that are transferred to the National Archives as permanent records publicly available through the National Archives Catalog, where they can be downloaded in a machine-readable format if that's what we received.  When records are transferred to us, we generally take as few actions as possible to reformat them in order to retain the authenticity of the records as they were created by the agency and then sent to us to preserve them and make them accessible.  I'm going to send your comment along to several teams at NARA for discussion.

**Comment by OwenAmbur** [comment]
Thanks for your prompt and thoughtful response.  It would be good if NARA could think beyond present circumstances to the time when agencies comply with the new law, including not only guidance NARA might provide to them to facilitate compliance but also how NARA itself will comply with respect to all of its own records.  Given appropriate metadata, virtually any records management function can be automated, and making records machine-readable means the content they contain can be treated as both data and metadata.
